name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/acne-scan-api:latest

      - name: Connect SSH and deploy container
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Stop and remove any existing container
            sudo docker stop ${{ secrets.CONTAINER_NAME }} 
            sudo docker rm ${{ secrets.CONTAINER_NAME }} 
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/acne-scan-api 

            # Run the new container
            sudo docker run --name ${{ secrets.CONTAINER_NAME }} -p 8080:8080 -d \
              -e DB_HOST=${{secrets.DB_HOST}} \
              -e DB_PORT=${{secrets.DB_PORT}} \
              -e DB_NAME=${{secrets.DB_NAME}} \
              -e DB_USERNAME=${{secrets.DB_USERNAME}} \
              -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
              ${{ secrets.DOCKERHUB_USERNAME }}/acne-scan-api

            # Run the migrations
            sudo docker exec ${{ secrets.CONTAINER_NAME }} migrate -database "mysql://${{secrets.DB_USERNAME}}:${{secrets.DB_PASSWORD}}@tcp(${{secrets.DB_HOST}}:${{secrets.DB_PORT}})/${{secrets.DB_NAME}}" -path /app/internal/infrastructure/database/migrations up
